### ISSUE TITLE
[Bug]: curl missing in images

### ISSUE THREAD

**Issue by mousabaker** [DockerToolbox/tfenv#1]
### What happened?

curl is missing resulting in command not found error when running `tfenv isntall x.x.x`

### Expected behavior

Being able to install terraform

### How do we reproduct the bug?

```bash
docker run -it wolfsoftwareltd/tfenv-alpine -c "tfenv install 1.2.0"
```

### Relevant log output

```shell
environment: line 4: curl: command not found
Failed to download remote versions from https://releases.hashicorp.com/terraform/
No versions matching '1.2.0' found in remote
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lupraxus** [comment]
Looks like a missing pre-req, thank you for raising this we will look to get that resolved asap. We are working on a new set of containers with a new frame work so will make sure this is added.

**Comment by Lupraxus** [comment]
docker run -it wolfsoftwareltd/tfenv-alpine -c "tfenv install 1.2.0"
Installing Terraform v1.2.0
Downloading release tarball from https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_linux_amd64.zip
######################################################################################################################################################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_SHA256SUMS
No keybase install found, skipping OpenPGP signature verification
terraform_1.2.0_linux_amd64.zip: OK
Archive:  /tmp/tfenv_download.IojedB/terraform_1.2.0_linux_amd64.zip
  inflating: terraform
Installation of terraform v1.2.0 successful. To make this your default version, run 'tfenv use 1.2.0'

**Comment by mousabaker** [comment]
Thanks for the quick fix! Works fine now.

**Comment by Lupraxus** [comment]
Excellent - glad it is all sorted.

**Comment by mousabaker** [comment]
FYI: I tried the other variants (debian, ubuntu etc) and they are also missing curl

**Comment by Lupraxus** [comment]
I will run some updates overnight and push new builds tomorrow.

**Comment by Lupraxus** [comment]
I have now updated all containers.
